namespace TswapCore;

/// <summary>
/// Generates a platform-appropriate install script for tswap.
/// The script is output to stdout for the user to review before running.
/// </summary>
public static class InstallScript
{
    private const string BinaryPathPlaceholder = "TSWAP_BINARY_PATH_PLACEHOLDER";

    private static readonly string BashLinuxTemplate = """
        #!/usr/bin/env bash
        # tswap install script — generated by: tswap installscript
        # Review this script, then run: bash installTswap.sh

        set -euo pipefail

        BINARY="TSWAP_BINARY_PATH_PLACEHOLDER"

        echo "==> Installing tswap binary..."

        # User-local install (no sudo required; used for non-sudo commands)
        mkdir -p "$HOME/.local/bin"
        cp -f "$BINARY" "$HOME/.local/bin/tswap"
        chmod +x "$HOME/.local/bin/tswap"
        echo "    Installed to ~/.local/bin/tswap"

        # System-wide install (required for 'sudo tswap' commands)
        sudo cp -f "$BINARY" /usr/local/bin/tswap
        sudo chmod +x /usr/local/bin/tswap
        echo "    Installed to /usr/local/bin/tswap"

        echo "==> Installing tswap skill (SKILL.md)..."
        mkdir -p "$HOME/.agents/skills/tswap"
        "$HOME/.local/bin/tswap" prompt > "$HOME/.agents/skills/tswap/SKILL.md"
        echo "    Written to ~/.agents/skills/tswap/SKILL.md"

        echo "==> Creating Claude Code symlink..."
        mkdir -p "$HOME/.claude/skills"
        [ -e "$HOME/.claude/skills/tswap" ] && ! [ -L "$HOME/.claude/skills/tswap" ] && rm -rf "$HOME/.claude/skills/tswap"
        ln -sfn "$HOME/.agents/skills/tswap" "$HOME/.claude/skills/tswap"
        echo "    Created ~/.claude/skills/tswap -> ~/.agents/skills/tswap"

        echo "==> Installing shell completions..."
        # bash: auto-loaded by bash-completion from the user data dir (no rc edit needed).
        BASH_COMP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions"
        mkdir -p "$BASH_COMP_DIR"
        "$HOME/.local/bin/tswap" completion bash > "$BASH_COMP_DIR/tswap"
        echo "    bash -> $BASH_COMP_DIR/tswap"
        # fish: auto-loaded from the completions dir when fish is installed.
        if command -v fish >/dev/null 2>&1; then
          FISH_COMP_DIR="$HOME/.config/fish/completions"
          mkdir -p "$FISH_COMP_DIR"
          "$HOME/.local/bin/tswap" completion fish > "$FISH_COMP_DIR/tswap.fish"
          echo "    fish -> $FISH_COMP_DIR/tswap.fish"
        fi
        # zsh: write the completion function; the dir must be on fpath (printed below).
        if command -v zsh >/dev/null 2>&1; then
          ZSH_COMP_DIR="$HOME/.zsh/completions"
          mkdir -p "$ZSH_COMP_DIR"
          "$HOME/.local/bin/tswap" completion zsh > "$ZSH_COMP_DIR/_tswap"
          echo "    zsh  -> $ZSH_COMP_DIR/_tswap"
          echo "         (if zsh completion doesn't load, add to ~/.zshrc: fpath+=$ZSH_COMP_DIR; autoload -Uz compinit; compinit)"
        fi
        echo "    Restart your shell to enable completion."

        echo ""
        echo "✅ tswap installed successfully."
        echo "   If ~/.local/bin is not on your PATH, add it:"
        echo "   echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
        """;

    private static readonly string BashMacOSTemplate = """
        #!/usr/bin/env bash
        # tswap install script — generated by: tswap installscript
        # Review this script, then run: bash installTswap.sh

        set -euo pipefail

        BINARY="TSWAP_BINARY_PATH_PLACEHOLDER"

        echo "==> Installing tswap binary..."
        sudo cp -f "$BINARY" /usr/local/bin/tswap
        sudo chmod +x /usr/local/bin/tswap
        echo "    Installed to /usr/local/bin/tswap"

        echo "==> Installing tswap skill (SKILL.md)..."
        mkdir -p "$HOME/.agents/skills/tswap"
        /usr/local/bin/tswap prompt > "$HOME/.agents/skills/tswap/SKILL.md"
        echo "    Written to ~/.agents/skills/tswap/SKILL.md"

        echo "==> Creating Claude Code symlink..."
        mkdir -p "$HOME/.claude/skills"
        [ -e "$HOME/.claude/skills/tswap" ] && ! [ -L "$HOME/.claude/skills/tswap" ] && rm -rf "$HOME/.claude/skills/tswap"
        ln -sfn "$HOME/.agents/skills/tswap" "$HOME/.claude/skills/tswap"
        echo "    Created ~/.claude/skills/tswap -> ~/.agents/skills/tswap"

        echo "==> Installing shell completions..."
        # bash: auto-loaded by bash-completion from the user data dir (no rc edit needed).
        BASH_COMP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions"
        mkdir -p "$BASH_COMP_DIR"
        /usr/local/bin/tswap completion bash > "$BASH_COMP_DIR/tswap"
        echo "    bash -> $BASH_COMP_DIR/tswap"
        # fish: auto-loaded from the completions dir when fish is installed.
        if command -v fish >/dev/null 2>&1; then
          FISH_COMP_DIR="$HOME/.config/fish/completions"
          mkdir -p "$FISH_COMP_DIR"
          /usr/local/bin/tswap completion fish > "$FISH_COMP_DIR/tswap.fish"
          echo "    fish -> $FISH_COMP_DIR/tswap.fish"
        fi
        # zsh: write the completion function; the dir must be on fpath (printed below).
        # macOS ships zsh as the default shell, so this is the common path here.
        if command -v zsh >/dev/null 2>&1; then
          ZSH_COMP_DIR="$HOME/.zsh/completions"
          mkdir -p "$ZSH_COMP_DIR"
          /usr/local/bin/tswap completion zsh > "$ZSH_COMP_DIR/_tswap"
          echo "    zsh  -> $ZSH_COMP_DIR/_tswap"
          echo "         (if zsh completion doesn't load, add to ~/.zshrc: fpath+=$ZSH_COMP_DIR; autoload -Uz compinit; compinit)"
        fi
        echo "    Restart your shell to enable completion."

        echo ""
        echo "✅ tswap installed successfully."
        """;

    private static readonly string PowerShellTemplate = """
        # tswap install script — generated by: tswap installscript
        # Review this script, then run: pwsh installTswap.ps1
        # Requires PowerShell 5.1 or later.

        $ErrorActionPreference = 'Stop'

        $Binary = "TSWAP_BINARY_PATH_PLACEHOLDER"

        Write-Host "==> Installing tswap binary..."

        # Install to WindowsApps — this directory is on PATH by default for the current user
        $InstallDir = "$env:USERPROFILE\AppData\Local\Microsoft\WindowsApps"
        New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
        Copy-Item -Force $Binary "$InstallDir\tswap.exe"
        Write-Host "    Installed to $InstallDir\tswap.exe"

        Write-Host "==> Installing tswap skill (SKILL.md)..."
        $SkillDir = "$env:USERPROFILE\.agents\skills\tswap"
        New-Item -ItemType Directory -Force -Path $SkillDir | Out-Null
        [System.IO.File]::WriteAllLines("$SkillDir\SKILL.md", (& "$InstallDir\tswap.exe" prompt))
        Write-Host "    Written to $SkillDir\SKILL.md"

        Write-Host "==> Creating Claude Code symlink..."
        $ClaudeSkillsDir = "$env:USERPROFILE\.claude\skills"
        New-Item -ItemType Directory -Force -Path $ClaudeSkillsDir | Out-Null
        $LinkPath = "$ClaudeSkillsDir\tswap"
        if (Test-Path $LinkPath) {
            Remove-Item -Recurse -Force $LinkPath
        }
        New-Item -ItemType Junction -Path $LinkPath -Target $SkillDir | Out-Null
        Write-Host "    Created $LinkPath -> $SkillDir"

        Write-Host "==> Installing shell completion (PowerShell)..."
        # PowerShell has no completion auto-load dir, so write the script and print the one
        # line to dot-source it from the profile (we don't edit the profile automatically).
        $CompletionFile = "$SkillDir\tswap.completion.ps1"
        [System.IO.File]::WriteAllLines($CompletionFile, (& "$InstallDir\tswap.exe" completion powershell))
        Write-Host "    Written to $CompletionFile"
        Write-Host "    To enable, add this line to your PowerShell profile (path in `$PROFILE):"
        Write-Host "        . `"$CompletionFile`""

        Write-Host ""
        Write-Host "✅ tswap installed successfully."
        """;

    /// <summary>
    /// Generates a bash install script for Linux.
    /// Installs to ~/.local/bin (user) and /usr/local/bin (system/sudo).
    /// </summary>
    public static string GetBashScript(string binaryPath)
        => BashLinuxTemplate.Replace(BinaryPathPlaceholder, binaryPath);

    /// <summary>
    /// Generates a bash install script for macOS.
    /// Installs to /usr/local/bin only (requires sudo).
    /// </summary>
    public static string GetMacOSScript(string binaryPath)
        => BashMacOSTemplate.Replace(BinaryPathPlaceholder, binaryPath);

    /// <summary>
    /// Generates a PowerShell install script for Windows.
    /// </summary>
    public static string GetPowerShellScript(string binaryPath)
        => PowerShellTemplate.Replace(BinaryPathPlaceholder, binaryPath);

    /// <summary>
    /// Generates the install script appropriate for the current platform.
    /// </summary>
    public static string GetScript(string binaryPath)
    {
        if (OperatingSystem.IsWindows()) return GetPowerShellScript(binaryPath);
        if (OperatingSystem.IsMacOS())  return GetMacOSScript(binaryPath);
        return GetBashScript(binaryPath);
    }
}
