namespace TswapCore;

/// <summary>
/// Generates a platform-appropriate install script for tswap.
/// The script is output to stdout for the user to review before running.
/// </summary>
public static class InstallScript
{
    private const string BinaryPathPlaceholder = "TSWAP_BINARY_PATH_PLACEHOLDER";

    private static readonly string BashTemplate = """
        #!/usr/bin/env bash
        # tswap install script — generated by: tswap installscript
        # Review this script, then run: bash installTswap.sh

        set -euo pipefail

        BINARY="TSWAP_BINARY_PATH_PLACEHOLDER"

        echo "==> Installing tswap binary..."

        # User-local install (no sudo required; used for non-sudo commands)
        mkdir -p "$HOME/.local/bin"
        cp -f "$BINARY" "$HOME/.local/bin/tswap"
        chmod +x "$HOME/.local/bin/tswap"
        echo "    Installed to ~/.local/bin/tswap"

        # System-wide install (required for 'sudo tswap' commands)
        sudo cp -f "$BINARY" /usr/local/bin/tswap
        sudo chmod +x /usr/local/bin/tswap
        echo "    Installed to /usr/local/bin/tswap"

        echo "==> Installing tswap skill (SKILL.md)..."
        mkdir -p "$HOME/.agents/skills/tswap"
        "$HOME/.local/bin/tswap" prompt > "$HOME/.agents/skills/tswap/SKILL.md"
        echo "    Written to ~/.agents/skills/tswap/SKILL.md"

        echo "==> Creating Claude Code symlink..."
        mkdir -p "$HOME/.claude/skills"
        if [ -L "$HOME/.claude/skills/tswap" ]; then
            rm "$HOME/.claude/skills/tswap"
        fi
        ln -s "$HOME/.agents/skills/tswap" "$HOME/.claude/skills/tswap"
        echo "    Created ~/.claude/skills/tswap -> ~/.agents/skills/tswap"

        echo ""
        echo "✅ tswap installed successfully."
        echo "   If ~/.local/bin is not on your PATH, add it:"
        echo "   echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
        """;

    private static readonly string PowerShellTemplate = """
        # tswap install script — generated by: tswap installscript
        # Review this script, then run: pwsh installTswap.ps1
        # Requires PowerShell 5.1 or later.

        $ErrorActionPreference = 'Stop'

        $Binary = "TSWAP_BINARY_PATH_PLACEHOLDER"

        Write-Host "==> Installing tswap binary..."

        # Install to WindowsApps — this directory is on PATH by default for the current user
        $InstallDir = "$env:USERPROFILE\AppData\Local\Microsoft\WindowsApps"
        New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
        Copy-Item -Force $Binary "$InstallDir\tswap.exe"
        Write-Host "    Installed to $InstallDir\tswap.exe"

        Write-Host "==> Installing tswap skill (SKILL.md)..."
        $SkillDir = "$env:USERPROFILE\.agents\skills\tswap"
        New-Item -ItemType Directory -Force -Path $SkillDir | Out-Null
        & "$InstallDir\tswap.exe" prompt | Out-File -Encoding utf8 "$SkillDir\SKILL.md"
        Write-Host "    Written to $SkillDir\SKILL.md"

        Write-Host "==> Creating Claude Code symlink..."
        $ClaudeSkillsDir = "$env:USERPROFILE\.claude\skills"
        New-Item -ItemType Directory -Force -Path $ClaudeSkillsDir | Out-Null
        $LinkPath = "$ClaudeSkillsDir\tswap"
        if (Test-Path $LinkPath) {
            Remove-Item -Force $LinkPath
        }
        New-Item -ItemType Junction -Path $LinkPath -Target $SkillDir | Out-Null
        Write-Host "    Created $LinkPath -> $SkillDir"

        Write-Host ""
        Write-Host "✅ tswap installed successfully."
        """;

    /// <summary>
    /// Generates a bash install script for Linux/macOS.
    /// </summary>
    public static string GetBashScript(string binaryPath)
        => BashTemplate.Replace(BinaryPathPlaceholder, binaryPath);

    /// <summary>
    /// Generates a PowerShell install script for Windows.
    /// </summary>
    public static string GetPowerShellScript(string binaryPath)
        => PowerShellTemplate.Replace(BinaryPathPlaceholder, binaryPath);

    /// <summary>
    /// Generates the install script appropriate for the current platform.
    /// </summary>
    public static string GetScript(string binaryPath)
        => OperatingSystem.IsWindows()
            ? GetPowerShellScript(binaryPath)
            : GetBashScript(binaryPath);
}
