namespace TswapCore.Keyring;

/// <summary>
/// Wrap/unwrap for a <see cref="SlotKind.Recovery"/> slot (issue #120,
/// <c>MULTI_MACHINE_KEYING.md</c> §The recovery slot: a bare keypair, not a CA-issued
/// certificate / §Per-backend wrap primitive: "Wrap <c>KEK_slot</c> to a bare X25519 (or EC)
/// keypair's public key — no PKI... Custody of the private key is the only control").
///
/// <para><b>Composition, not a new AEAD primitive.</b> A fresh ephemeral X25519 keypair is
/// minted at wrap time (<see cref="SlotKeyPair.Generate"/>), ECDH'd against the recovery
/// keypair's public key (<see cref="SlotKeyPair.ComputeSharedSecret"/>), and the shared secret
/// HKDF'd into a 32-byte KEK (<see cref="RecoverySlotKek.Derive"/>) — then the existing
/// <see cref="SlotPayloadWrap.Wrap"/>/<see cref="SlotPayloadWrap.Unwrap"/> AEAD layer does the
/// actual encryption, with the exact same AAD binding
/// (<c>formatVersion</c>/<c>vaultId</c>/<c>k</c>/<c>slotId</c>) every other slot kind uses. This
/// type only supplies a new way of producing the 32-byte KEK that primitive already expects.
/// </para>
///
/// <para><b>Recovery is possible without ever persisting the recovery private key</b> because
/// X25519 ECDH is symmetric: <c>ECDH(ephemeralPrivate, recoveryPublic)</c> computed here at wrap
/// time equals <c>ECDH(recoveryPrivate, ephemeralPublic)</c> computed later at recovery time.
/// The ephemeral public key travels in the clear as the slot's <see cref="Slot.PublicKey"/> (see
/// that field's doc comment on the two meanings of <c>PublicKey</c>); the ephemeral private key
/// is used once, here, and discarded.</para>
///
/// <para><b>Payload shape — <c>K_v</c> alone, not <see cref="SlotSecretPayload"/> (judgement
/// call, issue #120 PR body).</b> A machine slot's payload also carries that machine's own
/// re-wrap-capable X25519 keypair for #121's future <c>slot approve</c> flows targeting that
/// machine. A recovery slot has no "machine" to re-wrap for later — the recovery keypair itself,
/// held by the user outside the vault and never persisted by tswap, already serves that exact
/// role. Concatenating a second 32-byte field here would protect nothing real, so this type
/// passes <c>vaultKey</c> straight through to <see cref="SlotPayloadWrap"/> as the whole payload.
/// </para>
/// </summary>
public static class RecoverySlotWrap
{
    /// <summary>
    /// Wraps <paramref name="vaultKey"/> (<c>K_v</c>) to <paramref name="recoveryPublicKey"/>.
    /// Returns the freshly-minted ephemeral public key (destined for the recovery slot's
    /// <see cref="Slot.PublicKey"/>) alongside the wrapped bytes (destined for
    /// <see cref="Slot.Wrapped"/>). Throws <see cref="ArgumentException"/> if
    /// <paramref name="vaultKey"/> is not exactly <see cref="KeyringFormat.VaultKeySize"/> bytes
    /// — a programmer error, since it is always freshly generated by this codebase.
    /// </summary>
    public static (byte[] EphemeralPublicKey, byte[] Wrapped) Wrap(
        byte[] vaultKey, byte[] recoveryPublicKey, byte formatVersion, byte[] vaultId, byte k, byte[] slotId)
    {
        if (vaultKey.Length != KeyringFormat.VaultKeySize)
            throw new ArgumentException($"vaultKey must be {KeyringFormat.VaultKeySize} bytes", nameof(vaultKey));

        var ephemeral = SlotKeyPair.Generate();
        var sharedSecret = SlotKeyPair.ComputeSharedSecret(ephemeral.PrivateKey, recoveryPublicKey);
        var kek = RecoverySlotKek.Derive(sharedSecret, ephemeral.PublicKey);

        var wrapped = SlotPayloadWrap.Wrap(vaultKey, kek, formatVersion, vaultId, k, slotId);
        return (ephemeral.PublicKey, wrapped);
    }

    /// <summary>
    /// Recovers <c>K_v</c> given <paramref name="recoveryPrivateKey"/> (the credential only the
    /// user holds — never persisted anywhere by tswap) and the on-disk recovery slot's
    /// <paramref name="ephemeralPublicKey"/> (<see cref="Slot.PublicKey"/>) and
    /// <paramref name="wrapped"/> bytes (<see cref="Slot.Wrapped"/>). Redoes the ECDH (see this
    /// type's doc comment on DH symmetry), rederives the identical KEK, and unwraps.
    ///
    /// <para>Throws <see cref="TswapException"/> — never a raw crash — for a wrong
    /// <paramref name="recoveryPrivateKey"/>, a tampered <paramref name="wrapped"/> ciphertext,
    /// or a tampered AAD-bound field: X25519 ECDH always "succeeds" and produces 32 bytes even
    /// for an unrelated private key, so a wrong key surfaces only downstream, as
    /// <see cref="SlotPayloadWrap.Unwrap"/>'s AEAD authentication failure — the same
    /// indistinguishable-failure property <see cref="SlotPayloadWrap"/>'s own doc comment
    /// describes for every other slot kind.</para>
    /// </summary>
    public static byte[] Unwrap(
        byte[] wrapped, byte[] ephemeralPublicKey, byte[] recoveryPrivateKey,
        byte formatVersion, byte[] vaultId, byte k, byte[] slotId)
    {
        var sharedSecret = SlotKeyPair.ComputeSharedSecret(recoveryPrivateKey, ephemeralPublicKey);
        var kek = RecoverySlotKek.Derive(sharedSecret, ephemeralPublicKey);

        return SlotPayloadWrap.Unwrap(wrapped, kek, formatVersion, vaultId, k, slotId);
    }
}
